ERROR    uk_bin_collection.uk_bin_collection.get_bin_data:get_bin_data.py:127 Request Error: HTTPSConnectionPool(host='www.exeter.gov.uk', port=443): Max retries exceeded with url: /?User-Agent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F108.0.0.0+Safari%2F537.36 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fccc933bd40>, 'Connection to www.exeter.gov.uk timed out. (connect timeout=120)'))